# Generated by Django 2.2.5 on 2020-05-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='passwd',
            new_name='psw',
        ),
    ]
